In [1]:
!pip show tensorflow 

Name: tensorflow
Version: 2.16.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: C:\Users\Rishu Jaiswal\anaconda3\Lib\site-packages
Requires: tensorflow-intel
Required-by: 


In [2]:
import tensorflow
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input

In [3]:
import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import GlobalMaxPooling2D

# Create the ResNet50 base model
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False

# Create the Sequential model
model = tf.keras.Sequential([
    base_model,
    GlobalMaxPooling2D()
])


dummy_input = tf.zeros((1, 224, 224, 3))  # Create a dummy input tensor
output_shape = model(dummy_input).shape  # Pass the dummy input through the model to get the output shape

# Print the model summary
print(model.summary())

# Print the output shape of the model
print("Output shape:", output_shape)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ resnet50 (Functional)                │ (1, 7, 7, 2048)             │      23,587,712 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_max_pooling2d                 │ (1, 2048)                   │               0 │
│ (GlobalMaxPooling2D)                 │                             │                 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 23,587,712 (89.98 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 23,587,712 (89.98 MB)

None
Output shape: (1, 2048)


In [4]:
import numpy as np
from numpy.linalg import norm
def extract_features(img_path,model):
    img = image.load_img(img_path,target_size=(224,224))
    img_array = image.img_to_array(img)
    expanded_img_array = np.expand_dims(img_array, axis = 0)
    preprocessed_img = preprocess_input(expanded_img_array)
    result = model.predict(preprocessed_img).flatten()
    normalized_result = result/ norm(result)
    
    return normalized_result
    
    
    

In [5]:
import os

print(os.listdir("C:\\Users\\Rishu Jaiswal\\AI_TECH\\fashion-dataset\\fashion-dataset\\Test_image"))

['1163.jpg', '1164.jpg', '1165.jpg', '1525.jpg', '1526.jpg', '1528.jpg', '1529.jpg', '1530.jpg', '1531.jpg', '1532.jpg', '1533.jpg', '1534.jpg', '1535.jpg', '1536.jpg', '1537.jpg', '1538.jpg', '1539.jpg', '1540.jpg', '1541.jpg', '1542.jpg', '1543.jpg', '1544.jpg', '1545.jpg', '1546.jpg', '1547.jpg', '1548.jpg', '1549.jpg', '1550.jpg', '1551.jpg', '1552.jpg', '1553.jpg', '1554.jpg', '1555.jpg', '1556.jpg', '1557.jpg', '1558.jpg', '1559.jpg', '1561.jpg', '1562.jpg', '1563.jpg', '1565.jpg', '1566.jpg', '1567.jpg', '1569.jpg', '1570.jpg', '1571.jpg', '1572.jpg', '1573.jpg', '1575.jpg', '1577.jpg', '1578.jpg', '1579.jpg', '1580.jpg', '1581.jpg', '1582.jpg', '1583.jpg', '1584.jpg', '1587.jpg', '1588.jpg', '1590.jpg', '1591.jpg', '1592.jpg', '1594.jpg', '1595.jpg', '1596.jpg', '1597.jpg', '1598.jpg', '1599.jpg', '1603.jpg', '1604.jpg', '1605.jpg', '1607.jpg', '1608.jpg', '1609.jpg', '1610.jpg', '1611.jpg', '1612.jpg', '1613.jpg', '1614.jpg', '1615.jpg', '1616.jpg', '1617.jpg', '1618.jpg', '16

In [6]:
from tqdm import tqdm
filenames = []
for file in os.listdir("C:\\Users\\Rishu Jaiswal\\AI_TECH\\fashion-dataset\\fashion-dataset\\Test_image"):
    filenames.append(os.path.join('C:\\Users\\Rishu Jaiswal\\AI_TECH\\fashion-dataset\\fashion-dataset\\Test_image',file))
    
feature_list = []

for file in tqdm(filenames):
    feature_list.append(extract_features(file,model))

    
    
    

  0%|                                                                                          | 0/132 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


  1%|▌                                                                                 | 1/132 [00:02<04:29,  2.06s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


  2%|█▏                                                                                | 2/132 [00:02<02:02,  1.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step


  2%|█▊                                                                                | 3/132 [00:02<01:18,  1.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


  3%|██▍                                                                               | 4/132 [00:02<00:55,  2.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


  4%|███                                                                               | 5/132 [00:02<00:41,  3.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step


  5%|███▋                                                                              | 6/132 [00:03<00:39,  3.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step


  5%|████▎                                                                             | 7/132 [00:03<00:36,  3.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


  6%|████▉                                                                             | 8/132 [00:03<00:32,  3.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


  7%|█████▌                                                                            | 9/132 [00:03<00:27,  4.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


  8%|██████▏                                                                          | 10/132 [00:03<00:24,  4.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step


  8%|██████▊                                                                          | 11/132 [00:03<00:25,  4.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step


  9%|███████▎                                                                         | 12/132 [00:04<00:26,  4.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 10%|███████▉                                                                         | 13/132 [00:04<00:23,  4.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step


 11%|████████▌                                                                        | 14/132 [00:04<00:23,  5.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


 11%|█████████▏                                                                       | 15/132 [00:04<00:21,  5.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


 12%|█████████▊                                                                       | 16/132 [00:04<00:21,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 13%|██████████▍                                                                      | 17/132 [00:05<00:19,  5.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 14%|███████████                                                                      | 18/132 [00:05<00:18,  6.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step


 14%|███████████▋                                                                     | 19/132 [00:05<00:18,  6.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


 15%|████████████▎                                                                    | 20/132 [00:05<00:17,  6.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step


 16%|████████████▉                                                                    | 21/132 [00:05<00:17,  6.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


 17%|█████████████▌                                                                   | 22/132 [00:05<00:17,  6.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step


 17%|██████████████                                                                   | 23/132 [00:05<00:17,  6.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 18%|██████████████▋                                                                  | 24/132 [00:06<00:16,  6.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


 19%|███████████████▎                                                                 | 25/132 [00:06<00:16,  6.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


 20%|███████████████▉                                                                 | 26/132 [00:06<00:16,  6.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 20%|████████████████▌                                                                | 27/132 [00:06<00:16,  6.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 21%|█████████████████▏                                                               | 28/132 [00:06<00:16,  6.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


 22%|█████████████████▊                                                               | 29/132 [00:06<00:15,  6.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step


 23%|██████████████████▍                                                              | 30/132 [00:07<00:19,  5.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


 23%|███████████████████                                                              | 31/132 [00:07<00:18,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


 24%|███████████████████▋                                                             | 32/132 [00:07<00:17,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 25%|████████████████████▎                                                            | 33/132 [00:07<00:16,  5.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 26%|████████████████████▊                                                            | 34/132 [00:07<00:16,  6.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


 27%|█████████████████████▍                                                           | 35/132 [00:07<00:15,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


 27%|██████████████████████                                                           | 36/132 [00:08<00:15,  6.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 28%|██████████████████████▋                                                          | 37/132 [00:08<00:15,  6.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


 29%|███████████████████████▎                                                         | 38/132 [00:08<00:14,  6.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 30%|███████████████████████▉                                                         | 39/132 [00:08<00:14,  6.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step


 30%|████████████████████████▌                                                        | 40/132 [00:08<00:13,  6.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


 31%|█████████████████████████▏                                                       | 41/132 [00:08<00:13,  6.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


 32%|█████████████████████████▊                                                       | 42/132 [00:08<00:13,  6.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 33%|██████████████████████████▍                                                      | 43/132 [00:09<00:13,  6.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step


 33%|███████████████████████████                                                      | 44/132 [00:09<00:12,  6.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 34%|███████████████████████████▌                                                     | 45/132 [00:09<00:12,  7.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


 35%|████████████████████████████▏                                                    | 46/132 [00:09<00:12,  6.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


 36%|████████████████████████████▊                                                    | 47/132 [00:09<00:12,  6.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


 36%|█████████████████████████████▍                                                   | 48/132 [00:09<00:11,  7.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 37%|██████████████████████████████                                                   | 49/132 [00:09<00:11,  7.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 38%|██████████████████████████████▋                                                  | 50/132 [00:10<00:11,  7.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


 39%|███████████████████████████████▎                                                 | 51/132 [00:10<00:11,  6.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 39%|███████████████████████████████▉                                                 | 52/132 [00:10<00:11,  6.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 40%|████████████████████████████████▌                                                | 53/132 [00:10<00:11,  6.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


 41%|█████████████████████████████████▏                                               | 54/132 [00:10<00:11,  6.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 42%|█████████████████████████████████▊                                               | 55/132 [00:10<00:12,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 42%|██████████████████████████████████▎                                              | 56/132 [00:11<00:11,  6.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 43%|██████████████████████████████████▉                                              | 57/132 [00:11<00:11,  6.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 44%|███████████████████████████████████▌                                             | 58/132 [00:11<00:11,  6.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


 45%|████████████████████████████████████▏                                            | 59/132 [00:11<00:11,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 45%|████████████████████████████████████▊                                            | 60/132 [00:11<00:11,  6.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 46%|█████████████████████████████████████▍                                           | 61/132 [00:11<00:11,  6.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


 47%|██████████████████████████████████████                                           | 62/132 [00:12<00:11,  6.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 48%|██████████████████████████████████████▋                                          | 63/132 [00:12<00:10,  6.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 48%|███████████████████████████████████████▎                                         | 64/132 [00:12<00:10,  6.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


 49%|███████████████████████████████████████▉                                         | 65/132 [00:12<00:10,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


 50%|████████████████████████████████████████▌                                        | 66/132 [00:12<00:10,  6.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 51%|█████████████████████████████████████████                                        | 67/132 [00:12<00:10,  6.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


 52%|█████████████████████████████████████████▋                                       | 68/132 [00:12<00:10,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 52%|██████████████████████████████████████████▎                                      | 69/132 [00:13<00:10,  6.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


 53%|██████████████████████████████████████████▉                                      | 70/132 [00:13<00:09,  6.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


 54%|███████████████████████████████████████████▌                                     | 71/132 [00:13<00:09,  6.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step


 55%|████████████████████████████████████████████▏                                    | 72/132 [00:13<00:09,  6.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step


 55%|████████████████████████████████████████████▊                                    | 73/132 [00:13<00:10,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step


 56%|█████████████████████████████████████████████▍                                   | 74/132 [00:14<00:10,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step


 57%|██████████████████████████████████████████████                                   | 75/132 [00:14<00:10,  5.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


 58%|██████████████████████████████████████████████▋                                  | 76/132 [00:14<00:09,  5.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 58%|███████████████████████████████████████████████▎                                 | 77/132 [00:14<00:08,  6.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step


 59%|███████████████████████████████████████████████▊                                 | 78/132 [00:14<00:10,  5.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step


 60%|████████████████████████████████████████████████▍                                | 79/132 [00:14<00:10,  5.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step


 61%|█████████████████████████████████████████████████                                | 80/132 [00:15<00:09,  5.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step


 61%|█████████████████████████████████████████████████▋                               | 81/132 [00:15<00:10,  4.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step


 62%|██████████████████████████████████████████████████▎                              | 82/132 [00:15<00:10,  4.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step


 63%|██████████████████████████████████████████████████▉                              | 83/132 [00:15<00:11,  4.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step


 64%|███████████████████████████████████████████████████▌                             | 84/132 [00:16<00:11,  4.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step


 64%|████████████████████████████████████████████████████▏                            | 85/132 [00:16<00:11,  4.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


 65%|████████████████████████████████████████████████████▊                            | 86/132 [00:16<00:10,  4.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step


 66%|█████████████████████████████████████████████████████▍                           | 87/132 [00:16<00:09,  4.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


 67%|██████████████████████████████████████████████████████                           | 88/132 [00:16<00:08,  5.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


 67%|██████████████████████████████████████████████████████▌                          | 89/132 [00:17<00:07,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


 68%|███████████████████████████████████████████████████████▏                         | 90/132 [00:17<00:07,  5.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step


 69%|███████████████████████████████████████████████████████▊                         | 91/132 [00:17<00:07,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


 70%|████████████████████████████████████████████████████████▍                        | 92/132 [00:17<00:06,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


 70%|█████████████████████████████████████████████████████████                        | 93/132 [00:17<00:06,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


 71%|█████████████████████████████████████████████████████████▋                       | 94/132 [00:17<00:06,  5.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


 72%|██████████████████████████████████████████████████████████▎                      | 95/132 [00:18<00:06,  5.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step


 73%|██████████████████████████████████████████████████████████▉                      | 96/132 [00:18<00:06,  5.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


 73%|███████████████████████████████████████████████████████████▌                     | 97/132 [00:18<00:05,  5.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


 74%|████████████████████████████████████████████████████████████▏                    | 98/132 [00:18<00:05,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step


 75%|████████████████████████████████████████████████████████████▊                    | 99/132 [00:18<00:05,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


 76%|████████████████████████████████████████████████████████████▌                   | 100/132 [00:18<00:05,  5.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


 77%|█████████████████████████████████████████████████████████████▏                  | 101/132 [00:19<00:05,  6.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


 77%|█████████████████████████████████████████████████████████████▊                  | 102/132 [00:19<00:05,  5.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


 78%|██████████████████████████████████████████████████████████████▍                 | 103/132 [00:19<00:04,  5.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step


 79%|███████████████████████████████████████████████████████████████                 | 104/132 [00:19<00:04,  5.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


 80%|███████████████████████████████████████████████████████████████▋                | 105/132 [00:19<00:04,  5.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


 80%|████████████████████████████████████████████████████████████████▏               | 106/132 [00:19<00:04,  6.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


 81%|████████████████████████████████████████████████████████████████▊               | 107/132 [00:20<00:04,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


 82%|█████████████████████████████████████████████████████████████████▍              | 108/132 [00:20<00:04,  5.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


 83%|██████████████████████████████████████████████████████████████████              | 109/132 [00:20<00:03,  6.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


 83%|██████████████████████████████████████████████████████████████████▋             | 110/132 [00:20<00:03,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


 84%|███████████████████████████████████████████████████████████████████▎            | 111/132 [00:20<00:03,  6.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step


 85%|███████████████████████████████████████████████████████████████████▉            | 112/132 [00:20<00:03,  5.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step


 86%|████████████████████████████████████████████████████████████████████▍           | 113/132 [00:21<00:03,  5.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


 86%|█████████████████████████████████████████████████████████████████████           | 114/132 [00:21<00:03,  5.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step


 87%|█████████████████████████████████████████████████████████████████████▋          | 115/132 [00:21<00:02,  5.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


 88%|██████████████████████████████████████████████████████████████████████▎         | 116/132 [00:21<00:02,  5.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


 89%|██████████████████████████████████████████████████████████████████████▉         | 117/132 [00:21<00:02,  6.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 89%|███████████████████████████████████████████████████████████████████████▌        | 118/132 [00:21<00:02,  6.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


 90%|████████████████████████████████████████████████████████████████████████        | 119/132 [00:22<00:02,  6.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


 91%|████████████████████████████████████████████████████████████████████████▋       | 120/132 [00:22<00:01,  6.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


 92%|█████████████████████████████████████████████████████████████████████████▎      | 121/132 [00:22<00:01,  6.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


 92%|█████████████████████████████████████████████████████████████████████████▉      | 122/132 [00:22<00:01,  6.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


 93%|██████████████████████████████████████████████████████████████████████████▌     | 123/132 [00:22<00:01,  6.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


 94%|███████████████████████████████████████████████████████████████████████████▏    | 124/132 [00:22<00:01,  6.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step


 95%|███████████████████████████████████████████████████████████████████████████▊    | 125/132 [00:22<00:01,  6.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 95%|████████████████████████████████████████████████████████████████████████████▎   | 126/132 [00:23<00:00,  6.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


 96%|████████████████████████████████████████████████████████████████████████████▉   | 127/132 [00:23<00:00,  6.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


 97%|█████████████████████████████████████████████████████████████████████████████▌  | 128/132 [00:23<00:00,  6.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


 98%|██████████████████████████████████████████████████████████████████████████████▏ | 129/132 [00:23<00:00,  6.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


 98%|██████████████████████████████████████████████████████████████████████████████▊ | 130/132 [00:23<00:00,  6.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


 99%|███████████████████████████████████████████████████████████████████████████████▍| 131/132 [00:23<00:00,  6.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


100%|████████████████████████████████████████████████████████████████████████████████| 132/132 [00:24<00:00,  5.49it/s]


In [7]:
feature_list

[array([0.01674356, 0.10849487, 0.01362585, ..., 0.        , 0.03603915,
        0.02990709], dtype=float32),
 array([0.00792745, 0.11722136, 0.01789482, ..., 0.00371253, 0.01546775,
        0.02995877], dtype=float32),
 array([0.02705696, 0.02156647, 0.        , ..., 0.0079345 , 0.        ,
        0.02886755], dtype=float32),
 array([0.00440801, 0.04481736, 0.00817967, ..., 0.01032536, 0.00706475,
        0.00085735], dtype=float32),
 array([0.        , 0.03284022, 0.006135  , ..., 0.0063535 , 0.05752384,
        0.        ], dtype=float32),
 array([0.0031925 , 0.02115496, 0.00323056, ..., 0.        , 0.03165918,
        0.01117543], dtype=float32),
 array([0.02502976, 0.03262069, 0.00303117, ..., 0.02406443, 0.01129418,
        0.01880276], dtype=float32),
 array([0.02186187, 0.02674347, 0.00254134, ..., 0.02646738, 0.00814504,
        0.01513482], dtype=float32),
 array([0.        , 0.05168107, 0.00128268, ..., 0.01505324, 0.        ,
        0.01035539], dtype=float32),
 array([0.

In [10]:
print(np.array(feature_list).shape)

(132, 2048)


In [12]:
import pandas as pd
extracted_features_df=pd.DataFrame(feature_list)
extracted_features_df

0         1         2         3         4         5         6     \
0    0.016744  0.108495  0.013626  0.003791  0.000000  0.009039  0.019817   
1    0.007927  0.117221  0.017895  0.005206  0.013310  0.005422  0.023789   
2    0.027057  0.021566  0.000000  0.008298  0.002564  0.000038  0.026140   
3    0.004408  0.044817  0.008180  0.000635  0.024881  0.009360  0.003322   
4    0.000000  0.032840  0.006135  0.008018  0.012183  0.002373  0.004054   
..        ...       ...       ...       ...       ...       ...       ...   
127  0.010886  0.043884  0.000000  0.019042  0.000962  0.005288  0.023153   
128  0.014010  0.041942  0.000000  0.031901  0.000000  0.007595  0.019974   
129  0.005754  0.054399  0.010760  0.002073  0.000000  0.021180  0.024132   
130  0.007715  0.024263  0.000000  0.010165  0.009368  0.014490  0.031528   
131  0.000000  0.055430  0.001907  0.019439  0.004142  0.021317  0.040156   

         7         8         9     ...      2038      2039      2040  \
0    0.005525  0.004022  0.006196  ...  0.057314  0.010364  0.016461   
1    0.010967  0.000404  0.009620  ...  0.053740  0.008365  0.006098   
2    0.054689  0.000000  0.010843  ...  0.006494  0.005756  0.001171   
3    0.002923  0.008981  0.003228  ...  0.003263  0.004417  0.000000   
4    0.000000  0.000000  0.002682  ...  0.000838  0.014696  0.008568   
..        ...       ...       ...  ...       ...       ...       ...   
127  0.005172  0.000000  0.007133  ...  0.034093  0.004905  0.011771   
128  0.012921  0.000000  0.012657  ...  0.026043  0.005394  0.004629   
129  0.012696  0.000000  0.009076  ...  0.008085  0.000174  0.006239   
130  0.025713  0.000000  0.003353  ...  0.013226  0.007624  0.003728   
131  0.010821  0.000000  0.017094  ...  0.009547  0.008403  0.004560   

         2041      2042      2043      2044      2045      2046      2047  
0    0.005144  0.006544  0.007788  0.018945  0.000000  0.036039  0.029907  
1    0.013394  0.002149  0.001031  0.013817  0.003713  0.015468  0.029959  
2    0.054404  0.007674  0.000000  0.014976  0.007934  0.000000  0.028868  
3    0.000000  0.007979  0.003409  0.100969  0.010325  0.007065  0.000857  
4    0.000000  0.004164  0.002513  0.002589  0.006353  0.057524  0.000000  
..        ...       ...       ...       ...       ...       ...       ...  
127  0.069656  0.000000  0.000000  0.013715  0.012364  0.021259  0.019437  
128  0.033064  0.000622  0.000000  0.014486  0.030400  0.002662  0.028263  
129  0.051382  0.009115  0.017654  0.008119  0.020078  0.002034  0.009186  
130  0.017129  0.017362  0.000148  0.003274  0.020763  0.031152  0.017638  
131  0.063057  0.005800  0.000000  0.010410  0.012496  0.020657  0.016529  

[132 rows x 2048 columns]

In [13]:
import pickle
pickle.dump(feature_list,open('embeddings.pkl','wb'))
pickle.dump(filenames,open('filenames.pkl','wb'))